### ISSUE TITLE
manifest_to_docker_images fails as path is not splittable 

### ISSUE THREAD

**Issue by roytev** [devopshq/artifactory-cleanup#139]
`python-BaseException
Traceback (most recent call last):
  File "/artifactory-cleanup/artifactory_cleanup/artifactorycleanup.py", line 61, in cleanup
    artifacts_to_remove = policy.filter(artifacts)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/artifactory-cleanup/artifactory_cleanup/rules/base.py", line 286, in filter
    artifacts = rule.filter(artifacts)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/artifactory-cleanup/artifactory_cleanup/rules/docker.py", line 84, in filter
    artifacts = self._manifest_to_docker_images(artifacts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/artifactory-cleanup/artifactory_cleanup/rules/docker.py", line 49, in _manifest_to_docker_images
    artifact["path"], docker_tag = artifact["path"].rsplit("/", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
`

**Comment by jheinitz** [comment]
Same issue here. any chance to get the PR merged?

**Comment by allburov** [comment]
Sure, after one adds fallback logic! 

https://github.com/devopshq/artifactory-cleanup/pull/140/files#r1543990473

idk why the `path` doesn't have `repo/docker` format in some cases, but let's add a fallback:
1. Try to split 
2. If # of elements == 1 - use the new logic

**Comment by zhuamini-alt** [comment]
Submitted a fix PR for this crash: https://github.com/devopshq/artifactory-cleanup/pull/175

IssueHunt mirror: https://oss.issuehunt.io/r/devopshq/artifactory-cleanup/issues/139
