### ISSUE TITLE
Ignore-not-found issue

### ISSUE THREAD

**Issue by Skrgich** [devopshq/artifactory-cleanup#143]
I noticed that you fixed ignore-not-found issue with #138 but it still not working completely for me.

```
DESTROY MODE - delete *
NOT FOUND - *
DESTROY MODE - delete *
DESTROY MODE - delete *
Traceback (most recent call last):
   ...
  File "*.local/lib/python3.10/site-packages/artifactory_cleanup/artifactorycleanup.py", line 61, in cleanup
    policy.delete(artifact, destroy=self.destroy, ignore_not_found=self.ignore_not_found)
  File "*.local/lib/python3.10/site-packages/artifactory_cleanup/rules/base.py", line 321, in delete
    r.raise_for_status()
  File "*.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url:  ***LINK***
```
And when i open the link it looks like this:
```
{
  "errors": [
    {
      "status": 404,
      "message": "File not found."
    }
  ]
}
```
But it fails because it's checking only for status code 404. I fixed it locally by just adding code 500 to the exception.
I'm not sure if something's wrong with my artifactory or is it bug for artifactory-cleanup, if it is let me know and i can open a PR.

**Comment by allburov** [comment]
500 error with 404 in body - looks like artifactory (or infrastructure) issue, not the lib one.

**Comment by allburov** [comment]
if it returns 404 STATUS - the fix will work. Consider researching the artifactory issues or finding a way to handle it, it shouldn't return 500 in case of file not found
