### ISSUE TITLE
Python 3.12 - AttributeError: module 'pathlib' has no attribute '_Flavour'

### ISSUE THREAD

**Issue by shenxianpeng** [devopshq/artifactory-cleanup#150]
```
Successfully installed PyJWT-2.9.0 artifactory-cleanup-1.0.12 attrs-24.2.0 dohq-artifactory-0.10.1 hurry.filesize-0.9 plumbum-1.9.0 prettytable-3.11.0 pydash-8.0.3 python-dateutil-2.9.0.post0 teamcity-messages-1.32 treelib-1.7.0 typing-extensions-4.12.2 wcwidth-0.2.13
+ python3 cleanup.py --destroy --user test --password **** --artifactory-server https://artifactory.myorg.com/artifactory --config cleanup.py
Traceback (most recent call last):
  File "/mv/workspace/Infra/artifactory-repo-cleanup/happybee/artifactory/cleanup.py", line 1, in <module>
    from artifactory_cleanup import CleanupPolicy, rules
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory_cleanup/__init__.py", line 1, in <module>
    from artifactory_cleanup.cli import ArtifactoryCleanupCLI  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory_cleanup/cli.py", line 13, in <module>
    from artifactory_cleanup.artifactorycleanup import (
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory_cleanup/artifactorycleanup.py", line 9, in <module>
    from artifactory_cleanup.rules.base import ArtifactsList, CleanupPolicy, ArtifactDict
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory_cleanup/rules/__init__.py", line 3, in <module>
    from artifactory_cleanup.rules.docker import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory_cleanup/rules/docker.py", line 7, in <module>
    from artifactory import ArtifactoryPath
  File "/home/blwmv/.local/lib/python3.12/site-packages/artifactory.py", line 425, in <module>
    class _ArtifactoryFlavour(pathlib._Flavour):
                              ^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_Flavour'
```

This issue was caused by the upstream project issue https://github.com/devopshq/artifactory/issues/430

**Comment by allburov** [comment]
should work now!
