### ISSUE TITLE
destroy not deleting files on artifactory cloud

### ISSUE THREAD

**Issue by GitarPlayer** [devopshq/artifactory-cleanup#152]
here is my config file:

> 
    # artifactory-cleanup.yaml
    artifactory-cleanup:
      server: https://artifactory.mycompany.cloud:443/artifactory
      # $VAR is auto populated from environment variables
      user: myartuser
      password: myartpass
    
      policies:
        - name: Keep only the 5 latest Files in a folder
          rules:
            - rule: Repo
              name: "my-docker-repo"
            # Keep these tags for all images
            - rule: ExcludeDockerImages
              masks:
                - "*:latest"
            # Keep 5 docker tags for all images
            - rule: KeepLatestNFilesInFolder
              count: 5

here is the output with no --destroy:
podman run --rm -v "$(pwd)":/app devopshq/artifactory-cleanup:1.0.12 artifactory-cleanup
> 
    DEBUG - we would delete 'my-docker-repo/foo/395416' (f4f50deea25de1d51e80b9aee79d80165ac96cc1) - 159M
    Deleted artifacts count: 185
    Summary size: 31454366659
    
    +------------------------------------------+-------------+------+
    | Cleanup Policy                           | Files count | Size |
    +------------------------------------------+-------------+------+
    | Keep only the 5 latest Files in a folder |     185     | 29G  |
    |                                          |             |      |
    | Total size: 29G                          |             |      |
    +------------------------------------------+-------------+------+

the same with the --destroy flag:
podman run --rm -v "$(pwd)":/app devopshq/artifactory-cleanup:1.0.12 artifactory-cleanup --destroy
> 
    DESTROY MODE - delete 'my-docker-repo/foo/395416' (f4f50deea25de1d51e80b9aee79d80165ac96cc1) - 159M
    Deleted artifacts count: 186
    Summary size: 31639913831
    
    +------------------------------------------+-------------+------+
    | Cleanup Policy                           | Files count | Size |
    +------------------------------------------+-------------+------+
    | Keep only the 5 latest Files in a folder |     186     | 29G  |
    |                                          |             |      |
    | Total size: 29G                          |             |      |
    +------------------------------------------+-------------+------+
and running without the --destroy flag shows the same images again to be deleted and of course in artifactory cloud nothing is deleted:
podman run --rm -v "$(pwd)":/app devopshq/artifactory-cleanup:1.0.12 artifactory-cleanup
> 
    DEBUG - we would delete 'my-docker-repo/foo/395416' (f4f50deea25de1d51e80b9aee79d80165ac96cc1) - 159M(f4f50deea25de1d51e80b9aee79d80165ac96cc1) - 159M
    Deleted artifacts count: 186
    Summary size: 31639913831
    
    +------------------------------------------+-------------+------+
    | Cleanup Policy                           | Files count | Size |
    +------------------------------------------+-------------+------+
    | Keep only the 5 latest Files in a folder |     186     | 29G  |
    |                                          |             |      |
    | Total size: 29G                          |             |      |
    +------------------------------------------+-------------+------+

Interesting is also I use the exact same version to cleanup my onprem artifactory repo. And there it works like a charm. So, I guess it's related to artifactory cloud.

**Comment by GitarPlayer** [comment]
interestingly enough if I use devopshq/artifactory-cleanup:1.0.9 I do get an error message:
`
DESTROY MODE - delete my-docker-repo/foo/0.1.0-08b08154 - 183M'
Traceback (most recent call last):
  File "/usr/local/bin/artifactory-cleanup", line 8, in <module>
    sys.exit(ArtifactoryCleanupCLI())
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 177, in __new__
    return cls.run()
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/cli.py", line 175, in main
    for summary in cleanup.cleanup(
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/artifactorycleanup.py", line 61, in cleanup
    policy.delete(artifact, destroy=self.destroy)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/rules/base.py", line 320, in delete
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://artifactory.rch.cloud:443/artifactory/my-docker-repo/foo/0.1.0-08b08154`

this looks like a regression to me. If the serviceaccount indeed does not have the permissions then it should at least fail.
