### ISSUE TITLE
404 when destroy flag is set

### ISSUE THREAD

**Issue by atalakey4work** [devopshq/artifactory-cleanup#45]
Using "devopshq/artifactory-cleanup:latest" docker image i get 404 error.

Command:

artifactory-cleanup --destroy --user admin --password SOME_ASSWORD --artifactory-server https://SOME_URL --config rules.py

Output:

Filter artifacts - rule: repo - Apply the rule to one repository.
Filter artifacts - rule: exclude_docker_images - Exclude Docker images by name and tags.
Filter artifacts - rule: delete_docker_images_not_used - Removes Docker image not downloaded ``days`` days
Found 1534 artifacts AFTER filtering
DESTROY MODE - delete docker-local/SOME_IMAGE
Traceback (most recent call last):
  File "/usr/local/bin/artifactory-cleanup", line 8, in <module>
    sys.exit(ArtifactoryCleanup())
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 178, in __new__
    return cls.run()
  File "/usr/local/lib/python3.9/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/artifactorycleanup.py", line 179, in main
    cleanup_rule.delete(artifact, destroy=self._destroy)
  File "/usr/local/lib/python3.9/site-packages/artifactory_cleanup/rules/base.py", line 208, in delete
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://SOME_URL/docker-local/SOME_IMAGE

**Comment by atalakey4work** [comment]
Turns out that I had to add "/artifactory" to the URL "https://SOME_URL/artifactory/docker-local"
