### ISSUE TITLE
Multiple paths not working

### ISSUE THREAD

**Issue by AlexDaciuk** [devopshq/artifactory-cleanup#68]
Hi

I was trying to write some cleanup policies that make use of the multiple path feature, but it does not seem to work with the latest Artifactory version

Artifactory version :  7.41.12 rev 74112900
Artifactory-cleanup version : 0.4.2

Be aware that I ofuscated repo, microservice and url of our Artifactory

Cleanup Policies

```python
from artifactory_cleanup import rules
from artifactory_cleanup import CleanupPolicy
RULES = [
  CleanupPolicy(
  'Test',
  rules.Repo('npm-release-local'),
  rules.IncludePath(['*@scope/microservice*', '*microservice*']),
  rules.IncludeFilename('*-test*'),
  rules.KeepLatestNFiles(count=5),
  ),
]
```

Output

```
********************************************************************************
Verbose MODE
Simulating cleanup actions that will occur on 2022-09-13
Add AQL Filter - rule: Repo - Apply the rule to one repository.
Get from npm-release-local
Checking the existence of the npm-release-local repository
The npm-release-local repository exists
Add AQL Filter - rule: IncludePath - Apply to artifacts by path / mask.
Add AQL Filter - rule: IncludeFilename - Apply to artifacts by name/mask.
Add AQL Filter - rule: KeepLatestNFiles - Leaves the last (by creation time) files in the amount of N pieces. WITHOUT accounting subfolders
********************************************************************************
AQL Query:
Add AQL Text - rule: Repo - Apply the rule to one repository.
Add AQL Text - rule: IncludePath - Apply to artifacts by path / mask.
Add AQL Text - rule: IncludeFilename - Apply to artifacts by name/mask.
Add AQL Text - rule: KeepLatestNFiles - Leaves the last (by creation time) files in the amount of N pieces. WITHOUT accounting subfolders
Before AQL text: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scope/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat")
After AQL text: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scope/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]})

items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scope/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]})
********************************************************************************
Add AQL Text - rule: Repo - Apply the rule to one repository.
Add AQL Text - rule: IncludePath - Apply to artifacts by path / mask.
Add AQL Text - rule: IncludeFilename - Apply to artifacts by name/mask.
Add AQL Text - rule: KeepLatestNFiles - Leaves the last (by creation time) files in the amount of N pieces. WITHOUT accounting subfolders
Before AQL text: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scope/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat")
After AQL text: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scope/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]})

Traceback (most recent call last):
  File "/home/alex/.local/bin/artifactory-cleanup", line 8, in <module>
    sys.exit(ArtifactoryCleanupCLI())
  File "/home/alex/.local/lib/python3.10/site-packages/plumbum/cli/application.py", line 178, in __new__
    return cls.run()
  File "/home/alex/.local/lib/python3.10/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/home/alex/.local/lib/python3.10/site-packages/artifactory_cleanup/cli.py", line 114, in main
    for summary in cleanup.cleanup(
  File "/home/alex/.local/lib/python3.10/site-packages/artifactory_cleanup/artifactorycleanup.py", line 54, in cleanup
    artifacts = policy.get_artifacts()
  File "/home/alex/.local/lib/python3.10/site-packages/artifactory_cleanup/rules/base.py", line 214, in get_artifacts
    r.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://selfhosted.artifactory.com/artifactory/api/search/aql

```

And taking a look into our Artifactory logs we get this

```
2022-09-13T16:49:56.667Z [jfrt ] [ERROR] [247cfbc55f7e33d4] [o.a.r.r.a.AqlResource:101     ] [ttp-nio-8081-exec-26] - Fail to execute query: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, 
{"path": {"$match": ["*@scoped/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]}): 

Failed to parse query: items.find({"$and": [{"repo": {"$eq": "npm-release-local"}}, {"path": {"$match": ["*@scoped/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]}), 
it looks like there is syntax error near the following sub-query: ["*@scoped/microservice*", "*microservice*"]}}, {"name": {"$match": "*-test*"}}]}).include("*", "property", "stat").sort({"$asc" : ["created"]})
```

We get the same error trying to use multiple items in `IncludeFilename` , if we write two separated cleanup policies they work just fine 

Thanks
Alex

**Comment by allburov** [comment]
@AlexDaciuk yep, it's the issue, thank you for noticing it!
I'll fix it on the next release which is coming soon https://github.com/devopshq/artifactory-cleanup/pull/63

**Comment by AlexDaciuk** [comment]
great!
